features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
theme_skin: ''
enable_customize: '1'
sticky_menu: '1'
site_layout: wide
preloader: '0'
default_header: header
footer_skin: ''
footer_first_size: '3'
footer_second_size: '2'
footer_third_size: '3'
footer_four_size: '4'
customize_css: ''
map_source: google
mapbox_access_token: ''
mapbox_id_style: mapbox.light
google_key: AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU
hide_header_button_link: show
header_button_link: /node/add/listing
map_center_latitude: '40.6797079'
map_center_longitude: '-73.9465289'
map_zoom: '14'
google_map_style: ''
listing_search_action: listings
